### PR TITLE
Ins 18

### PR DESCRIPTION
**Pull request by zturo**
fixed some typo and added ability to hide alerts

### CODE REVIEW

**Comment by zturo** [comment]
Added some demo function for the DEMO ^^

**Comment by zturo** [comment]
Pls add the "hotfix user registration/login error" commit to the develop branch. It will help...

**Comment by recurzive** [comment]
Hi Zsolt,

Pls see comments from your previous pull request!!!

**Comment by zturo** [comment]
Can we pls discuss it on chat?

**Comment by abodo** [comment]
Of course.

**Pull request closed without merging**
